/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Profile: () => import('#controllers/profile_controller'),
  Projects: () => import('#controllers/projects_controller'),
  Skills: () => import('#controllers/skills_controller'),
}
