/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ProfileSchema extends BaseModel {
  static $columns = ['about', 'createdAt', 'email', 'github', 'id', 'linkedin', 'location', 'name', 'profileImage', 'resume', 'title', 'updatedAt'] as const
  $columns = ProfileSchema.$columns
  @column()
  declare about: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare github: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare linkedin: string | null
  @column()
  declare location: string | null
  @column()
  declare name: string | null
  @column()
  declare profileImage: string | null
  @column()
  declare resume: string | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'githubUrl', 'id', 'image', 'liveUrl', 'technologies', 'title', 'updatedAt'] as const
  $columns = ProjectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare githubUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: string | null
  @column()
  declare liveUrl: string | null
  @column()
  declare technologies: string | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SkillSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = SkillSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
